### ISSUE TITLE
Feature Request: Create uber pom from root and children (modules)

### ISSUE THREAD

**Issue by jayefem** [raydac/uber-pom#1]
The current implementation creates an uber pom from a pom and its parents. 

It would be also nice to create an uber pom which is based on the root pom and its children (modules).

Example:

Directory structure:
myproject/pom.xml
myproject/mysubmodule1/pom.xml
myproject/mysubmodule2/pom.xml

Execute:
$ cd myproject
$ mvn com.igormaznitsa:uber-pom:upom

Result:
myproject/pom.xml
myproject/uber-pom.xml
myproject/mysubmodule1/pom.xml
myproject/mysubmodule2/pom.xml

where uber-pom.xml contains the dependecies (e.g.) of myproject/pom.xml, mysubmodule1/pom.xml and mysubmodule2/pom.xml

**Comment by raydac** [comment]
could you describe a use case? is there any maven project which needs add child dependencies into parent?

**Comment by jayefem** [comment]
Refactoring. Our project has too much unnecessary modules. We want to move all into one big project.

You answered to a similar question on Stackoverflow; that's why I stumbled over your plugin:
http://stackoverflow.com/questions/4880087/maven-plugin-for-merging-pom-xml-files/30557002#30557002

**Comment by raydac** [comment]
every module of a maven project builds its own artefact and you define dependencies which needed only for the artefact, in the parent pom you define common dependencies and mainly the parent pom just contain  list and common dependencies for child modules 

could you make small test maven project which could show your scenario and I could use it that as a test ans understand the use case

**Comment by jayefem** [comment]
Hi Igor,

I've attached "project before" and "project after" zip files. Zipfiles 
are hopefully supported by github. I also sent this reply to your 
official email address in case it is not supported.

Explanation:

project before:
- Main module with dependencyManagement
- Two submodules with different dependencies. Some are duplicates, some 
  have version conflicts (see comments)

project after:
- Only one main module without submodules
- All dependencyManagement and dependencies are merged in one pom
- The duplicates in the pom are removed
- Ideally the dependencies are sorted afterwards (not mandatory as there 
  is already a Maven Plugin which provides that feature)
- Conflict dependecies are all listed. Maven will display a warning by 
  compile time. However your Maven Plugin does not care about it because 
  resolving the conflict has to be done manually.
- The code is also moved into one src folder. Again, that is not of the 
  business of your Maven Plugin. It has to be done manually with help of 
  the underlying version control (e.g. "git mv")

Why does somebody needs that? We have multiple projects with tenth of 
submodules and want to consolidate them into one big project because the 
current architecture was a mistake. Too much submodules are confusing in 
our case. Therefore we want to refactor the project structure.

Please let me know if you need more information.

Thanks,
Jan

Am 11.07.2015 um 09:17 schrieb Igor Maznitsa:

**Comment by raydac** [comment]
ok, I have got the email contains zip files, thank you very much
as I understand you need add some merging function for a maven project tree with generation of new maven project without children in separated folder, am I right? it is not exact business of  the uber-pom plugin but I think it is possible to extend the plugin to support such functionality and I will implement that

**Comment by jayefem** [comment]
Cool! Yes, exactly. It's a merge.
