### ISSUE TITLE
Feature Request: deleteOnExit=false

### ISSUE THREAD

**Issue by jayefem** [raydac/uber-pom#2]
"deleteOnExit" seems not to work. When calling this:
mvn com.igormaznitsa:uber-pom:upom -DdeleteOnExit=false
The result is still:
"NB! The Result uber-pom file marked to be removed after JVM session"

Please enable "deleteOnExit" as commandline parameter and set the default value to "false" as it is  confusing when there is no result.

**Comment by raydac** [comment]
added support of 'upom.delete.on.exit' system property to override deleteOnExit parameter, the system property has bigger priority

**Comment by jayefem** [comment]
Cool! Don't forget to update the documentation.
